version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: user_postgres
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
